# Base URL
base.url=http://172.19.71.28:8080/OrderSystem2026Phase1

# MQTT
mqtt.host=tcp://172.19.71.28:1883

# Database
db.host=172.19.71.28
db.port=3306
db.name=order_management
db.user=order
db.password=1234