# Base URL（Tomcatのサービス名 "web" を指定）
base.url=http://web:8080/OrderSystem2026Phase1

# MQTT（Mosquittoのサービス名 "mqtt-broker" を指定）
mqtt.host=tcp://mqtt-broker:1883

# Database（MySQLのサービス名 "db" を指定）
db.host=db
db.port=3306
db.name=order_management
db.user=order
db.password=1234